INSERT INTO blog_posts (title, slug, excerpt, content, cover_image, is_published, published_at, tags)
VALUES
('The Evolution of the Arsenal Kit', 'evolution-of-arsenal-kit', 'A deep dive into how the iconic red and white evolved over the decades.', 'Full content goes here...', 'https://images.unsplash.com/photo-1518605368461-1ee12523999e?auto=format&fit=crop&q=80', true, NOW(), ARRAY['History', 'Arsenal']),
('Top 10 Kits of the 90s', 'top-10-kits-90s', 'The 90s produced some of the most vibrant and memorable football kits. Here are our top 10.', 'Full content goes here...', 'https://images.unsplash.com/photo-1600250395378-963b2f567b55?auto=format&fit=crop&q=80', true, NOW(), ARRAY['Listicle', '90s']),
('Why We Love Classic Goalkeeper Kits', 'classic-goalkeeper-kits', 'A look back at the bold, bizarre, and brilliant goalkeeper shirts of the past.', 'Full content goes here...', 'https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?auto=format&fit=crop&q=80', true, NOW(), ARRAY['Goalkeeper', 'Retro']),
('The Best World Cup Kits in History', 'best-world-cup-kits', 'Celebrating the greatest designs worn on the biggest stage in world football.', 'Full content goes here...', 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&q=80', true, NOW(), ARRAY['World Cup', 'History']),
('Umbro: A Design Retrospective', 'umbro-design-retrospective', 'Tracing the legacy of one of footballs most iconic kit manufacturers.', 'Full content goes here...', 'https://images.unsplash.com/photo-1587384475454-e0c1b752496a?auto=format&fit=crop&q=80', true, NOW(), ARRAY['Umbro', 'Brand']),
('A Guide to Collecting Match-Worn Shirts', 'guide-match-worn-shirts', 'Tips and tricks for finding and authenticating rare match-worn football shirts.', 'Full content goes here...', 'https://images.unsplash.com/photo-1518605368461-1ee12523999e?auto=format&fit=crop&q=80', true, NOW(), ARRAY['Collecting', 'Guide']),
('The Impact of Sponsors on Kit Design', 'impact-sponsors-kit-design', 'How front-of-shirt sponsors changed the aesthetics of football kits forever.', 'Full content goes here...', 'https://images.unsplash.com/photo-1600250395378-963b2f567b55?auto=format&fit=crop&q=80', true, NOW(), ARRAY['Design', 'Sponsors']),
('Iconic Serie A Kits of the 1980s', 'iconic-serie-a-kits-1980s', 'Revisiting the golden era of Italian football and its stylish kits.', 'Full content goes here...', 'https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?auto=format&fit=crop&q=80', true, NOW(), ARRAY['Serie A', '1980s']),
('How Nike Revolutionized Football Apparel', 'nike-revolution-football-apparel', 'Exploring Nike’s journey from a newcomer to a dominant force in football kits.', 'Full content goes here...', 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&q=80', true, NOW(), ARRAY['Nike', 'History']),
('The Worst Kits Ever Worn', 'worst-kits-ever-worn', 'Sometimes designers get it wrong. A look at some of the most controversial football kits.', 'Full content goes here...', 'https://images.unsplash.com/photo-1587384475454-e0c1b752496a?auto=format&fit=crop&q=80', true, NOW(), ARRAY['Humor', 'Design'])
ON CONFLICT (slug) DO NOTHING;
